In [1]:
import numpy as np  
a=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])  
b=np.array([[11, 21, 31], [42, 52, 62], [73, 83, 93]])  
c=np.append(a,b)  
c  

array([10, 20, 30, 40, 50, 60, 70, 80, 90, 11, 21, 31, 42, 52, 62, 73, 83,
       93])

In [4]:
import numpy as np  
a1= np.arange(6).reshape((2,3))  
a1  
b=np.transpose(a)  
b  

array([[1, 3],
       [2, 4]])

In [6]:
import numpy as np  
a2= np.array([[1, 2], [3, 4]])  
b2=np.mean(a2)  
print(b2)  
x = np.array([[5, 6], [7, 34]])  
y=np.mean(x)  
print(y)  

2.5
13.0


In [9]:
import numpy as np  
aa=np.unique([1,2,3,4,3,6,2,4])  
aa  

array([1, 2, 3, 4, 6])